dist: xenial
language: python
python:
  - 3.7
  - 3.8
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8
